var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/audit-seo-ia/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0gx51~3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_060d1m.._.js")
R.c("server/chunks/ssr/node_modules_next_dist_04rgm_y._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0o.j_c5.js")
R.c("server/chunks/ssr/[root-of-the-server]__0bhp-w9._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0b53.np._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_@opentelemetry_api_index_0zv0b3p.js")
R.c("server/chunks/ssr/_0y9grhs._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_audit-seo-ia_page_actions_0wp-ag1.js")
R.m(90326)
module.exports=R.m(90326).exports
