// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[slug]" | "/admin" | "/admin/audit-seo" | "/admin/leads" | "/admin/leads/[id]" | "/applications-metier" | "/assistant-ia-telephone" | "/audit-ia" | "/audit-ia/success" | "/audit-seo-ia" | "/automatisation-entreprise" | "/blog" | "/blog/[slug]" | "/contact" | "/crm-ia-pme" | "/expertise-ia-corse" | "/intelligence-artificielle-corse" | "/realisations" | "/services"
type AppRouteHandlerRoutes = "/api/admin/seo-audit/cache" | "/api/admin/seo-audit/run" | "/api/admin/seo-exports" | "/api/audit-seo" | "/api/cron/lead-reminders" | "/api/google/analytics/events" | "/api/google/analytics/overview" | "/api/google/analytics/pages" | "/api/google/auth" | "/api/google/callback" | "/api/google/search-console/performance" | "/api/google/search-console/sites"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = "/[[...path]]"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[[...path]]": { "path"?: string[]; }
  "/[slug]": { "slug": string; }
  "/admin": {}
  "/admin/audit-seo": {}
  "/admin/leads": {}
  "/admin/leads/[id]": { "id": string; }
  "/api/admin/seo-audit/cache": {}
  "/api/admin/seo-audit/run": {}
  "/api/admin/seo-exports": {}
  "/api/audit-seo": {}
  "/api/cron/lead-reminders": {}
  "/api/google/analytics/events": {}
  "/api/google/analytics/overview": {}
  "/api/google/analytics/pages": {}
  "/api/google/auth": {}
  "/api/google/callback": {}
  "/api/google/search-console/performance": {}
  "/api/google/search-console/sites": {}
  "/applications-metier": {}
  "/assistant-ia-telephone": {}
  "/audit-ia": {}
  "/audit-ia/success": {}
  "/audit-seo-ia": {}
  "/automatisation-entreprise": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/contact": {}
  "/crm-ia-pme": {}
  "/expertise-ia-corse": {}
  "/intelligence-artificielle-corse": {}
  "/realisations": {}
  "/services": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
