// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(seo-pages)/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[slug]">> = Specific
  const handler = {} as typeof import("../../app/(seo-pages)/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/audit-seo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/audit-seo">> = Specific
  const handler = {} as typeof import("../../app/admin/audit-seo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/leads/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/leads/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/leads/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/leads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/leads">> = Specific
  const handler = {} as typeof import("../../app/admin/leads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/applications-metier/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/applications-metier">> = Specific
  const handler = {} as typeof import("../../app/applications-metier/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/assistant-ia-telephone/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assistant-ia-telephone">> = Specific
  const handler = {} as typeof import("../../app/assistant-ia-telephone/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/audit-ia/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audit-ia">> = Specific
  const handler = {} as typeof import("../../app/audit-ia/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/audit-ia/success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audit-ia/success">> = Specific
  const handler = {} as typeof import("../../app/audit-ia/success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/audit-seo-ia/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audit-seo-ia">> = Specific
  const handler = {} as typeof import("../../app/audit-seo-ia/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/automatisation-entreprise/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/automatisation-entreprise">> = Specific
  const handler = {} as typeof import("../../app/automatisation-entreprise/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../app/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/crm-ia-pme/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/crm-ia-pme">> = Specific
  const handler = {} as typeof import("../../app/crm-ia-pme/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/expertise-ia-corse/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expertise-ia-corse">> = Specific
  const handler = {} as typeof import("../../app/expertise-ia-corse/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/intelligence-artificielle-corse/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/intelligence-artificielle-corse">> = Specific
  const handler = {} as typeof import("../../app/intelligence-artificielle-corse/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/realisations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/realisations">> = Specific
  const handler = {} as typeof import("../../app/realisations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services">> = Specific
  const handler = {} as typeof import("../../app/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/seo-audit/cache/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/seo-audit/cache">> = Specific
  const handler = {} as typeof import("../../app/api/admin/seo-audit/cache/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/seo-audit/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/seo-audit/run">> = Specific
  const handler = {} as typeof import("../../app/api/admin/seo-audit/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/seo-exports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/seo-exports">> = Specific
  const handler = {} as typeof import("../../app/api/admin/seo-exports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/audit-seo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit-seo">> = Specific
  const handler = {} as typeof import("../../app/api/audit-seo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cron/lead-reminders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/lead-reminders">> = Specific
  const handler = {} as typeof import("../../app/api/cron/lead-reminders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/google/analytics/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/google/analytics/events">> = Specific
  const handler = {} as typeof import("../../app/api/google/analytics/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/google/analytics/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/google/analytics/overview">> = Specific
  const handler = {} as typeof import("../../app/api/google/analytics/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/google/analytics/pages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/google/analytics/pages">> = Specific
  const handler = {} as typeof import("../../app/api/google/analytics/pages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/google/auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/google/auth">> = Specific
  const handler = {} as typeof import("../../app/api/google/auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/google/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/google/callback">> = Specific
  const handler = {} as typeof import("../../app/api/google/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/google/search-console/performance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/google/search-console/performance">> = Specific
  const handler = {} as typeof import("../../app/api/google/search-console/performance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/google/search-console/sites/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/google/search-console/sites">> = Specific
  const handler = {} as typeof import("../../app/api/google/search-console/sites/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
